[tool.poetry]
name = "streamlit-tutorial"
version = "0.1.0"
description = ""
authors = ["kent"]

[tool.poetry.dependencies]
python = "*"
numpy = "*"
scipy = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.9"
